const C = {
  INSTRUCTION_DISPLAY_URL: "bitwits.pc.codes",

  TIMER_COUNTDOWN_INTERVAL: 30,
  TIMER_SAFETY_BUFFER: 1000,

  MAX_PROMPT_CHARS: 140,
  MAX_ANSWER_CHARS: 60,
  MAX_NAME_CHARS: 18,
};

module.exports = C;
